site_name: Selkies
site_url: https://selkies-project.github.io/selkies
site_description: >-
  Open-Source Low-Latency Accelerated Linux WebRTC HTML5 Remote Desktop Streaming Platform for Self-Hosting, Containers, Kubernetes, or Cloud/HPC

theme:
  name: material

# Repository
repo_name: Selkies
repo_url: https://github.com/selkies-project/selkies

# Copyright
copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> <a href="https://github.com/selkies-project/selkies" target="_blank" rel="noopener">Selkies Project</a>. All rights reserved.

# Configuration
theme:
  name: material
  # custom_dir: overrides
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo/favicon.ico
  logo: assets/logo/icon-512x512.png
  icon:
    admonition:
      quote: octicons/quote-16

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Additional configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/selkies-project/selkies
    - icon: fontawesome/brands/discord
      link: https://discord.gg/wDNGDeSW5F

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  # - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Navigation
nav:
  - Home: README.md
  - 'What is Selkies?': design.md
  - 'Getting Started': start.md
  - Usage: usage.md
  - 'Troubleshooting and FAQs': faq.md
  - 'WebRTC and Firewall Issues': firewall.md
  - Components: component.md
  - 'Development and Contributions': development.md
