# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Validate devcontainer-feature.json files

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      packages: read
    steps:
    - uses: actions/checkout@v4

    - name: "Validate devcontainer-feature.json files"
      uses: devcontainers/action@v1
      with:
        validate-only: "true"
        base-path-to-features: ".devcontainer/features/desktop-selkies"
